gap-packages/recog

- gap/almostsimple/lietype.gi
- gap/c3c5.gi
- gap/c6.gi
- gap/d247.gi
Eamonn is currently looking through the code with us to figure out where the 'undocumented' algorithms come from.
> Add Citations to C3C5 and C6 files

- gap/almostsimple.gi
- gap/matimpr.gi
- gap/tensor.gi
When Eamon O'Brien visited us we had the impression, that these functions/files were not used. @fingolfin do you think that is still true?
> Annotate some unused functions/files

- gap/base/recognition.gi
We don't (yet) have tests where GeneratorsOfGroup returns an empty list, but I want to add some in future.
When tests run on many groups, it can be hard to tell which failed -- this adds more information so tests can be reproduced easily.
> Small testing fixes / improvements

- doc/recognition.xml
...unless I'm completely confused, that is.
> Recognition info record is component object, not positional object

- gap/generic/TrivialGroup.gi
- gap/matrix.gi
- tst/broken/quick/MatReducible.tst
- tst/broken/quick/ProjLowIndex.tst
- tst/broken/quick/ProjReducible.tst
- tst/broken/slow/ProjC6.tst
- tst/broken/veryslow/MatC6.tst
- tst/working/quick/MatTrivial.tst
- tst/working/quick/PermTrivial.tst
- tst/working/quick/ProjLowIndex.tst
See also issue #101; the second commit is taken from PR #87 (albeit in modified form) by @ChrisJefferson 
Fixes #84
Fixes #91
> Disable some secretely broken tests, and add validation check to SLPforElementFunc for trivial groups

- makedoc.g
> update required version of AutoDoc

- regen_doc.g
> Make regen_doc.g more portable

- .travis.yml
I would like Travis to run tests on all of the branches on my fork, not just master.
> Test all pushed branches on Travis

- .travis.yml
- PackageInfo.g
- tst/broken/quick/Sporadic.tst
- tst/working/quick/Sporadic.tst
- switch from trusty to xenial for newer versions of everything
- don't bother testing a 32bit variant
- but do test against stable GAP branches in addition to master
- remove obsolete env variables
> Update Travis settings

- gap/base/projective.gi
Is this kind of thing welcome? I enjoy doing it anyway, even though arguably I could be doing something more productive.
I took a look at this file, and thought that I could both shorten the code and make it clearer what is happening.
I'm not sure whether the `Assert`s (and their levels) are appropriate.
> Refactor and add comments to base/projective.gi

- PackageInfo.g
This PR consists of three things:
- Changes the subtitle of the package and hence resolves #165 
- Adds new contributors to `PackageInfo.g` and hence resolves #164. I have done this to the best of my knowledge. If somebody is missing, please point me to them and I will update this PR. 
- Remove all postal adresses.
> Adjust subtitle, contributors and postal adresses

- .github/workflows/CI.yml
Results at: https://github.com/ssiccha/recog/actions
> Use custom action

- tst/naming.g
- tst/working/quick/ClassicalNaturalNaming.tst
> Improve tests for naming classical groups in nat rep

- tst/working/quick/PermLargeBasePrimitive.tst
Adds test for LargeBasePrimitive.
~~Moves two broken sporadic test cases.~~
> Add test for LargeBasePrimitive

- gap/base/recognition.gi
Add comments documenting the variables involved in `RandomElm`,
`RandomElmOrd`, and `GetElmOrd`.
Restructures `RandomElm`, `RandomElmOrd`, and `GetElmOrd` a little.
Removes the check that `r.nr` must be positive from an if-branch in
`GetElmOrd`.  The input record `r` is always generated by `RandomElm`.
That function always sets `r.nr` to a positive number.
> Improve RandomElm, RandomElmOrd, GetElmOrd

- gap/base/methsel.gi
I find the "at a higher tolerance level" formulation confusing.
> Improve comment

- README.md
Fixed and revived version of #238.
> Update Codecov badge

- doc/howtowritearecogmethod.autodoc
I'm putting this here so that I don't forget to do it. The wording definitely can still be improved. Suggestions welcome!
> Add section on elms with memory to method howto

- gap/base/recognition.gd
Namely for:
- RecognitionInfoFamily
- IsRecognitionInfo
- RIFac
- RIKer
> Add synonyms for renamed variables

- gap/base/recognition.gd
- gap/base/recognition.gi
The documentation was very vague. Write into the documentation what the
package currently does with the flag IsReady.
> Clarify docs of IsReady

- .github/workflows/CI.yml
- PackageInfo.g
However, keep running tst/testall.g in CI
> Change package TestFile to tst/testquick.g

- doc/recognition.xml
- gap/base/recognition.gd
- gap/base/recognition.gi
- gap/generic/KnownNilpotent.gi
- gap/projective/almostsimple.gi
... to avoid clashes with tons of existing code
> Rename order to OrderFunc

- gap/projective/c6.gi
- misc/dependencies.txt
It has been part of the GAP library for a long time now
> Remove SMTX_InvariantBilinearForm

- gap/projective/d247.gi
> Fix an unexpected error in RECOG.DirectFactorsFinder
