gap-packages/recog

- doc/intro.xml
- doc/methods.xml
- doc/recognition.xml
- gap/base/recognition.gd
- gap/base/recognition.gi
This code did nothing. It is also clear in which kind of situation
it would ever be called.
In any case, we can easily add it back should we ever come into a
situation where it seems useful, but for now, it just distracts
people who try to learn how recog works.
> Remove blackbox code

- tst/slow/NonDeletedPermModuleRepOfSn.tst
Currently, if e.g. an Sn is given acting on a module that is not a
deleted permutation module, recognition is very inefficient.
An example is given in the file examples/NonDeletedPermModuleRepOfSn.g
> Add example for recognizing An and Sn on non deleted permutation modules

- doc/recog.bib
As you can see here <https://gap-packages.github.io/recog/doc/chapBib.html>, the non-ASCII characters are not displaying properly. I've just tried replacing them with the actual characters, and it seems to work fine.
> Use non-ASCII characters directly in the bib

- gap/perm.gi
The method `StabilizerChain` in `FindHomDbPerm` uses the genss package.
This commits inserts a link to the genss package homepage into the
description string of the `StabilizerChain` method.
> FindHomDbPerm: Add link to genss package into description string of `StabilizerChain` method

- gap/base/recognition.gi
- tst/quick/PermCycle.tst
This makes tests print even more information, and also adds some configurable options.
The main new feature, testing elements not in the group, is disabled by default as it fails for almost everything. A cycle perm test is added just to test this option works.
> Add options and improve printing of tests

- doc/intro.xml
- doc/methods.xml
- doc/recog.bib
- gap/almostsimple/lietype.gi
These are the works cited at the top of `gap/almostsimple/lietype.gi`. I have replaced that text with the key for these works in the bibliography.
Since these new references are not actually cited yet in the documentation, they don't appear in the bibliography of the documentation when it is compiled. Is there a way of forcing all entries to appear in the bibliography, even though they're not cited (yet)? I'm not yet sure where the appropriate place would be in the manual to cite them yet.
_(This PR also fixes a tiny typo that I found, in a separate commit.)_
> Add two entries to the bibliography

- doc/afterrecog.xml
- doc/recognition.xml
Obviously this is not important to merge, and if it's conflicting with ongoing documentation work then it can wait. It doesn't conflict with anything that the documentation team is working on, however.
> Doc: tag fail, false, true as keywords, rather than code

- doc/recog.bib
Sorry, my fault, that's a bit embarrassing. This was causing errors when compiled the documentation. I also removing some repeated lines.
> Add a missing comma to the bib file

- gap/base/recognition.gi
- gap/perm.gi
- tst/quick/PermAllSubgroups.tst
- tst/working/quick/Sporadic.tst
* Make SLPforElement work on the identity group.
* Move stabilizerchains into the structure tree instead of stored in the group (where there might be already be a different stabilizer chain).
* Add tests for these things
* Add a general test function to test all subgroups of a group, and use.
* Add a function to test all subgroups of an atlas group (not yet called)
* Move a test, which ended up in the wrong place after some merges.
> Various fixes

- doc/methods.xml
- doc/recog.bib
For some reason there were several annoying LaTeX errors when using the full URL to Max's habilitation thesis. So I've just shortened it to a link to the GitHub repo.
I also changed a duplicated label name in the documentation.
> Remove some documentation compilation warnings

- gap/perm.gi
In `FindHomMethodsPerm.PcgsForBlocks` it is checked whether `subgens` is `fail`, but it is probably `pcgs` meant.
I think this didn't cause any problems as it is checked in `FindHomMethodsPerm.Pcgs` again. So this test is then maybe not necessary any longer. Also `pcgs` is currently computed twice, but maybe should be stored.
Done by @monschau, @munsee and me (the code part of the documentation group) on the SummerSchoolMGR.
> In FindHomMethodsPerm.PcgsForBlocks subgens can never be fail

- doc/recognition.xml
- gap/base/recognition.gi
Improve documentation of findgensNmeth.
- Fix an example
- doc now states findgensNmeth has to have two components.
Rename local variable in RecogniseGeneric.
> Improve findgensNmeth

- gap/perm.gi
- gap/snksetswrsr.gi
- Rewrites the documentation for SnkSetswrSr. States more precisely
what is meant by "large-base primitive group", that is
which groups are recognised.
Fixes #75.
> Improve documentation of SnkSetswrSr method

- gap/matrix.gi
- gap/perm.gi
Most functions in gap/perm.gi are commented in the code now. In case they appear in the documentation they also have now an AutoDoc entry.
Additionally some functions in gap/matrix.gi got a documenting comment.
Done by @monschau, @Munsee and me (the code part of the documentation group) on the SummerSchoolMGR.
> Improve documentation of functions in code and manual II

- PackageInfo.g
Sure, a release date is kind of irrelevant for a development version. But I'd still feel happier with the date being the correct last release date rather than one with the wrong year.
> PackageInfo.g: correct last release date

- PackageInfo.g
- README.md
- doc/install.xml
- doc/intro.xml
Mostly this is about advertising the mailing list.
I've also added something about the required packages to the installation page of the documentation, which was taken from the README. In doing so, I decided to have the required packages listed in a consistent (alphabetical) order.
> Documentation: add more information about feedback options

- gap/AnSnOnFDPM.gi
- gap/almostsimple.gi
- gap/base/methsel.gi
- gap/base/recognition.gi
- gap/c3c5.gi
- gap/c6.gi
- gap/classicalnatural.gi
- gap/d247.gi
- gap/generic/KnownNilpotent.gi
- gap/matrix.gi
- gap/perm.gi
- gap/ppd.gi
- gap/tensor.gi
- makedoc.g
- regen_doc.g
- tst/testsporadicrecog.g
I did this everywhere that I thought appropriate (in particular, I didn't change `misc/` or `contrib/`; I changed most occurrences in `gap/`).
An error is usually triggered when something wrong has happened. `Error` lets you return after this, and continue the computation, which is almost always a bad idea if something genuinely wrong has happened. `ErrorNoReturn` only lets you quit the computation after an error, which seems like the most sensible option in most cases.
> Replace many "Error"s with "ErrorNoReturn"

- doc/afterrecog.xml
- doc/methsel.xml
- doc/recognition.xml
- gap/almostsimple.gi
- gap/base/methsel.gd
- gap/base/recognition.gd
- gap/base/recognition.gi
The other manpages should also be moved into GAPDoc comments;
and these then in turn could be converted to AutoDoc comments.
But for now, this is a start and could serve as template for
others who might want to help.
> doc: move parts of the manual into GAPDoc source comments

- gap/classical.gi
There's nothing wrong with the old code for `IsPowerOfPrime`, but I expected that GAP would have a built-in function to do the same, and being GAP, it would probably be faster. That seemed to be near enough the case: there exists `IsPrimePowerInt`, which while much more complicated than this function, seems to perform well. Using it, I get the following speedup:
```
gap> Number([1 .. 10000000], n -> IsPowerOfPrimeOLD(n, 2)); time;
23
17340
gap> Number([1 .. 10000000], n -> IsPowerOfPrimeNEW(n, 2)); time;
23
2624
```
(Note that `IsPowerOfPrime` is only ever called for the prime `2` in recog. But the new one is faster for everything I tested.)
In the spirit of keeping `recog` simple, I propose that we merge this PR and reduce the amount of code in the package.
> Simplify and speed up IsPowerOfPrime

- doc/recognition.xml
- gap/base/recognition.gd
- gap/base/recognition.gi
- gap/matrix.gi
- gap/perm.gi
- tst/broken/veryslow/ClassicalNatural.tst
- tst/working/quick/PermThrowAwayFixedPoints.txt
- tst/working/slow/basic.tst
- tst/working/veryslow/ClassicalNatural.tst
This adds a new attribute, HomomSourceCheck, which checks if a value is in the source of Homom.
This is needed (I believe) to let us reject invalid elements of groups, but I'm open to discussion.
(EDIT: was called Range, that was the wrong name).
> Add ValidateHomomInput, and use it to fix ThrowAwayFixedPoints

- doc/recognition.xml
I think that we should attempt to compile the documentation as part of the CI tests, which I have now mentioned in #151.
> Make the documentation compile again: change a tag </P> -> <P/>

- doc/afterrecog.xml
- gap/perm.gi
- tst/working/slow/basic.tst
This resolves #141.
If people object to the renaming, then I don't mind dropping that commit.
> Fix documentation for and rename Perm.VeryFewPoints

- gap/base/recognition.gi
- gap/perm.gi
- gap/perm/giant.gi
- tst/broken/veryslow/PermSym8Subgroups.tst
- tst/working/veryslow/PermSym10Subgroup.tst
- tst/working/veryslow/PermTrans16.tst
This is an extension of #98, which adds many more homomrangecheck calls, and also fixes an SLP bug in An and Sn.
WIth this (as the tests show), we can now hit all Subgroups of Sym(10), and all transitive groups of size 16. These numbers are chosen just to be large enough and run in "reasonable" time.
If we push much larger than this we start failing failures, but those are due to only recognising a subgroup instead of the whole group, not SLP/element problems.
This contains #98
> More homomrangecheck

- contrib/frank/guessq.g
- gap/almostsimple.gi
- gap/c3c5.gi
- gap/c6.gi
- gap/classical.gi
- gap/d247.gi
- gap/generic/FewGensAbelian.gi
- gap/matimpr.gi
- gap/matrix.gi
- gap/perm.gi
- gap/tensor.gi
- gap/tools.gi
I looked through several files one evening last week, and for fun I started to make some mostly superficial changes as I went along. The idea with this PR is to go some small way to making the code in the package more readable, and also more consistent with what I know of the GAP world. Sorry if this is overwhelming to review.
Here are the main things that I've done:
* I broke one-line conditions `if condition then something; fi;` into three-liners.
* I removed brackets around simple negations, i.e. `not(single_condition)` -> `not single_condition`.
* I joined some consecutive and compatible `if ... fi; if ... fi;` bits of code with `elif`s.
* I used `StringFormatted` to clean up some messy `Info` messages.
* I slightly improved `RECOG.IsDiagonalBlockOfMatrix` in `gap/matrix.gi`.
* I …
> Tweak and reformat code in several files

- gap/base/hack.g
- tst/testall.g
The order of the random source and the matrix/vector will be swapped, to match
the order used by `Random` and other similar functions. The code in this
commit should work equally well with old and new GAP versions.
> Don't call RANDOM_SEED; Update Randomize installation to future GAP versions

- doc/methsel.xml
- gap/base/methsel.gd
- gap/base/methsel.gi
- gap/example/cyclic2.gi
- gap/matrix.gi
- gap/matrix/classical.gi
- gap/perm.gi
- gap/projective.gi
Change AddMethod to now take two arguments: the method database and a record which contains the method to be added and information about it. 
Setting the InfoClass InfoAddMethod to 1 now produces messages when AddMethod is called with unbound method.validatesInput component.
I added a few small changes to the documentation. The PR is now ready for review.
Now we can address #107 method for method.
> Extend AddMethod

- gap/base/recognition.gd
Either the documentation of `RecogniseGroup` is incorrect, or the function
itself is incorrect. See the discussion in #181.
> Fix RecogniseGroup wrt sorting hints

- gap/projective.gi
- gap/projective/almostsimple.gi
- gap/projective/almostsimple/threeelorders.gi
- read.g
The source comment now explains why RECOG.grouplist only stores two
largest element orders.
It claimed that ThreeLargeElOrders could also handle sporadic groups.
However, neither does the paper [KS09] which describes the algorithm
mention sporadic groups, nor does did I find anything relating to
sporadic groups in the function.
I tested this by taking matrix representation via AtlasGenerators for
M11, Co2 and J2 and then calling ComputeSimpleSocle and
ThreeLargeElOrders. ThreeLargeElOrders returned fail in all three cases.
Say that it recognises lie groups and computes their characteristic.
> Improvements to three element orders

- gap/perm.gi
In #131 @PaulaHaehndel and co-authors added things like `<C>FindHomMethodsPerm.Imprimitive</C>` to certain parts of the autodoc documentation. I came along and blithely changed this to `<Ref Subsect="Imprimitive" Style="Text"/>` and similar, dropping the `FindHomMethodsPerm` bit. But I have now learnt that it was a deliberate choice to include in #131 (see https://github.com/gap-packages/recog/pull/131#discussion_r301122826)
I've tried to find a compromise. How do we feel about this? It renders fine in the manual, and I think looks fine in the code too. If we like it, I can do this in other appropriate places of the documentation.
> Improve referencing in documentation in some parts of perm.gi

- gap/perm/largebase.gi
Fixes a comment in perm/largebase.gi and improves LargeBasePrimitive.
Documents explicitly that LargeBasePrimitive can not handle fixed points.
Moves the NkrGetParameters call to the front, so that LargeBasePrimitive
can exit as soon as it knows that it is not applicable.
If LargeBasePrimitive is successfull, then it creates an isomorphism. So
there is nothing to do for the kernel.
> Improve LargeBasePrimitive

- gap/base/recognition.gi
- gap/generic/KnownNilpotent.gi
- gap/matrix.gi
- gap/matrix/classical.gi
- gap/matrix/matimpr.gi
- gap/matrix/ppd.gi
- gap/matrix/slconstr.gi
- gap/perm/largebase.gi
- gap/projective.gi
- gap/projective/AnSnOnFDPM.gi
- gap/projective/almostsimple.gi
- gap/projective/c6.gi
- gap/projective/classicalnatural.gi
- gap/projective/d247.gi
- gap/projective/findnormal.gi
- gap/projective/tensor.gi
- gap/tools.gi
This allows us to see in code coverage reports which of those returns are actually being taken.
> Ensure return statements are on a line of their own

- gap/matrix/slconstr.gi
- tst/working/quick/ProjSubfield3.tst
General clean up.
Comments out unused code for natural SL recognition.
Adjusts the unused FindHomMethodsMatrix.NaturalSL to only try the constructive recognition method 10 times. Then returns TemporaryFailure.
Move a broken test.
Fix documentation of RecogniseGeneric.
> Miscellaneous changes

- doc/howtowritearecogmethod.autodoc
- doc/methsel.xml
- gap/generic/TrivialGroup.gi
- gap/matrix.gi
- gap/perm.gi
- gap/projective.gi
> doc: how to write a recognition method

- .github/workflows/CI.yml
Just a couple of small changes to bring this into line with the example package.
Also, I don't think there's a need to compile the documentation on every test job, so I've removed that. It should save some seconds.
(I also don't think it's necessary to explicitly clone AutoDoc).
> Tweak GitHub Actions

- doc/methods.xml
- regen_doc.g
- adds a table of all unused methods to the manual
- at the start of each method, insert by which database it is used
Fixes #257.
> Enhance regen_doc.g

- gap/matrix/slconstr.gi
- add a header comment which of these functions is actually used
- document SLCR.FindHom
- reference SLCR.FindHom in the documentation of
FindHomMethodsMatrix.NaturalSL
TODO: the documentation of SLCR.FindHom does not appear in the manual.
@fingolfin, could you point me to the file I need to change? I had a look but didn't find anything.
> Improve doc of gap/matrix/slconstr.gi

- doc/intro.xml
- doc/recognition.xml
- gap/base/recognition.gd
- Remove "Conventions" sections from the docs
- We don't have any conventions. That we only handle finite fields should
rather go into the introduction.
- Fix a typo
- Document that we can only handle finite fields
> Remove convention sections

- doc/afterrecog.xml
- doc/howtowritearecogmethod.autodoc
- doc/recognition.xml
- doc/renaming.xml
- doc/renaming_index.xml
- doc/renaming_table.xml
- gap/base/recognition.gd
- gap/base/recognition.gi
- gap/generic/KnownNilpotent.gi
- gap/generic/SnAnUnknownDegree.gi
- gap/generic/kernel.gi
- gap/matrix.gi
- gap/matrix/matimpr.gi
- gap/perm.gi
- gap/projective.gi
- gap/projective/d247.gi
- makedoc.g
- misc/colva/Evaluate.g
- misc/colva/Rearrange.g
- misc/colva/Refine.g
- misc/colva/TopPerms.g
- misc/colva/leaves.g
- misc/colva/stuff.g
- tst/broken/quick/L43d2.tst
- tst/broken/veryslow/ClassicalNatural.tst
- tst/testclassicalnatural.g
- tst/working/quick/PermLargeBasePrimitive.tst
- tst/working/quick/bugfix.tst
- tst/working/quick/mixed.tst
- tst/working/veryslow/ClassicalNatural.tst
RecognitionInfoFamily -> RecogNodeFamily
IsRecognitionInfo -> IsRecogNode
RIFac -> ImageRecogNode
RIKer -> KernelRecogNode
PR 1 for #177
> Improve and unify names

- tst/testslow.g
- tst/testveryslow.g
- tst/working/veryslow/MatFDPM.tst
Add testslow.g and testveryslow.g. I'd like to have these so that I can run the three test suites in parallel.
Currently `TestRecogGL(6,27);;` fails. This should we fixed once we have
mandarins though.
Also adds a comment.
> Add testslow.g and testveryslow.g

- gap/base/recognition.gi
The first commit fixes a bug in RandomElm. This fix is needed to call RandomElm
on a group which does not store its random elements.
The second commit removes a TODO. The following is of course not a proper
benchmark, but just a comparison of two runs of `tst/testall.g`. I think it's good enough to warrant that commit though. I originally wrote the comparison only for `tst/testquick.g` but using `tst/testall.g` gives the same overall picture.
Storing the random elements makes the whole test suite and most test
files finish roughly 10% earlier than without storing random elements.
There are a few tests which run almost two times as fast with storing
random elements enabled by default compared to without it being enabled.
There are a few test files where both approaches take roughly the …
> Remove TODO: is storing random elms quicker?

- doc/howtowritearecogmethod.autodoc
- doc/recognition.xml
- doc/renaming.xml
- doc/renaming_index.xml
- doc/renaming_table.xml
- gap/base/recognition.gd
- gap/base/recognition.gi
- gap/generic/KnownNilpotent.gi
- gap/matrix.gi
- gap/matrix/matimpr.gi
- gap/perm.gi
- gap/projective.gi
- gap/projective/almostsimple.gi
- gap/projective/c3c5.gi
- gap/projective/c6.gi
- gap/projective/d247.gi
- gap/projective/tensor.gi
- misc/colva/Evaluate.g
- misc/colva/Rearrange.g
- misc/colva/Refine.g
- misc/colva/TopPerms.g
- misc/colva/leaves.g
- misc/colva/stuff.g
- misc/obsolete/derived.gi
- misc/obsolete/semilinear.gi
- misc/obsolete/shortorbs.gi
This continues #253.
Renames as follows:
`RIParent` -> `ParentRecogNode`
`methodsforfactor` -> `methodsforimage`
`forfactor` -> `InitDataForImageRecogNode`
`forkernel` -> `InitDataForKernelRecogNode`
The documentation builds on my machine and I've checked a few cross-references and index entries. Everything looks fine there. `testquick.g` also passes on my machine. 
**Edit**: I've moved the whole nice generators business into a separate branch.
> Improve and unify names (2)

- gap/base/recognition.gi
- gap/projective.gi
- gap/projective/almostsimple.gi
- gap/projective/almostsimple/lietype.gi
- gap/projective/classicalnatural.gi
- gap/projective/d247.gi
- tst/working/quick/bugfix.tst
Slightly change how nodes are printed. Previously, the name of the
successful method might be appended by a `comment` string. Now, if
there is a comment, it is printed in a separate `Comment:` field.
Thus also remove the leading underscore of the `ri!.comment` values.
> Improve printing of recog trees

- gap/base/recognition.gi
This snippet in RecogniseGeneric is not used by anything. If somebody
needs it, it's easy to reproduce. Thus remove it.
> Remove unused projection slp code

- doc/recognition.xml
- gap/base/recognition.gd
- gap/base/recognition.gi
- gap/projective/almostsimple.gi
- misc/colva/DPleaf.g
- misc/colva/Evaluate.g
- misc/colva/Rearrange.g
- misc/colva/Refine.g
- misc/colva/SimpleRecog.g
- misc/colva/leaves.g
- read.g
- tst/broken/quick/Sporadic.tst
- tst/working/combined/Sporadic.tst
- tst/working/quick/GenericSnAnUnknownDegree.tst
- tst/working/slow/GenericSnAnUnknownDegree.tst
- Improve documentation of IsReady
- Improve RecogniseGeneric
- Clean up of comments.
- Some refactoring.
- Improve the warning message if recognition of a node does not
terminate. Since IsReady is not set, an error will be thrown once one
wants do something with the recognition data structure. Thus it is not
necessary to throw an error in RecogniseGeneric. Make
sure that, if everything went fine, then IsReady is set directly
before returning.
- Rename and document recognition node constructor
- Also rename the corresponding type.
Rename as follows:
RecognitionInfoType -> RecogNodeType
EmptyRecognitionInfoRecord -> RecogNode
> Improve RecogniseGeneric and document RecogNode

- gap/base/recognition.gd
Resolves this warning:
```
#W WARNING: non resolved reference: rec(
Oper := "\\\\in" )
```
With this change, the reference is correctly cross-linked.
> Fix reference to \in

- gap/base/recognition.gd
... to avoid breaking the matgrp test suite.
This should be reverted again at some point in the future, once a successor for matgrp 0.70 has been released.
> Temporary disable obsolete warning for RIFac/RIKer
